### ISSUE TITLE
Initiation Checklist

### ISSUE THREAD

**Issue by bargle0** [bargle0/kanban#2]
- [x] Are you a scrub?
- [x] Do you know any scrubs on the team?
- [x] Solve all the problems.
